baseURL = "https://www.kserickson.com"
languageCode = "en-us"
title = "K.S.Erickson"
theme="archie"
copyright = "© kserickson"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=3 # articles per page

[params]
	mode="auto" # color-mode → light,dark or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "I am a Senior Director at [Anduril Industries](https://www.anduril.com/), where I'm helping to build the future of Air Defense. For almost ten years I worked on a variety of problems at [Palantir Technologies](https://www.palantir.com/), including delivering on complex DHS and DOD contracts, and operationalizing commitments to protecting privacy and civil liberties. In a previous life I was a PhD student in Political Theory at Georgetown, where I will forever be ABD."

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/kserickson"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/_kserickson/"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

#[[menu.main]]
#name = "About"
#url = "/about"
#weight = 3

#[[menu.main]]
#name = "Tags"
#url = "/tags"
#weight = 4